name: My First CI Pipeline

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello from GitHub Actions
        run: echo "🎉 Hello from my first CI pipeline!"

