name: Hello World Pipeline

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "✅ Hello World from GitHub Actions!"

